# Generated by Django 5.1.3 on 2024-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='イベント名')),
                ('event_date', models.DateField(verbose_name='日程候補')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
            ],
        ),
    ]
