# Generated by Django 5.1.3 on 2024-12-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('public', '公開中'), ('closed', '締め切り')], default='draft', max_length=10),
        ),
        migrations.CreateModel(
            name='EventDateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_options', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('availability', models.CharField(choices=[('o', '◯'), ('x', '✕'), ('d', '△')], max_length=1)),
                ('date_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.eventdateoption')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='event.event')),
            ],
        ),
    ]
