# Generated by Django 5.1.3 on 2024-11-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
